spring:
  datasource:
     username: natparks
     password: natparks
     url: jdbc:mysql://localhost:3306/Natparks
     
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
     
     
  sql:
    init:
      mode: always  
     
         